version: '3.8'

services:
  dev-db_back:
    container_name: dev_database_back
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
    - back-db_network
networks:
  back-db_network: